language: go

cache:
  directories:
    - ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}/vendor
    - ${GOPATH}/src/github.com/fzipp
    - ${GOPATH}/src/github.com/golang
    - ${GOPATH}/src/github.com/gordonklaus
    - ${GOPATH}/src/github.com/h12w
    - ${GOPATH}/src/github.com/mattn

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
sudo: false

env:
    CI_SERVICE=travis-ci

install:
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/fzipp/gocyclo
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/h12w/gosweep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/mattn/goveralls
  - go get gonum.org/v1/gonum/stat
  - go get gopkg.in/cheggaaa/pb.v1
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/exp/rand

script:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh
